{block_params: {K: [[424.6064659125572, 0.0, 302.62477665348985], [0.0, 425.6259206559359,
        276.32211219330236], [0.0, 0.0, 1.0]], R: [[-0.05649842532150532], [-3.0633799663577834],
      [-0.2680961631560443]], T: [[12.081784817362529], [27.65451956772551], [156.65232978134537]]},
  card_params: {K: [[424.6064659125572, 0.0, 302.62477665348985], [0.0, 425.6259206559359,
        276.32211219330236], [0.0, 0.0, 1.0]], R: [[-0.05649842464294062], [-3.0633799724723074],
      [-0.2680961609569755]], T: [[14.580760488301818], [20.667873792706267], [195.9580509377627]]}}
