black:
  max:
  - 89
  - 255
  - 255
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 197
  - 144
  - 107
  min:
  - 110
  - 83
  - 67
green:
  max:
  - 224
  - 104
  - 255
  min:
  - 140
  - 0
  - 143
red:
  max:
  - 255
  - 255
  - 255
  min:
  - 0
  - 178
  - 117
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
